Repository jenkinsci/gitea-checks-plugin, pull requests merged in 2024-06, with the labels that each got.

#134 Switch to renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: chore, developer

#137 fix CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#139 Fix spotbugs and checkstyle
  src/main/java/io/jenkins/plugins/checks/gitea/GitSCMChecksContext.java
  src/main/java/io/jenkins/plugins/checks/gitea/GiteaChecksContext.java
  src/main/java/io/jenkins/plugins/checks/gitea/GiteaChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/gitea/GiteaSCMSourceChecksContext.java
  src/main/java/io/jenkins/plugins/checks/gitea/SCMFacade.java
  src/test/java/io/jenkins/plugins/checks/gitea/GiteaChecksPublisherITest.java
  src/test/java/io/jenkins/plugins/checks/gitea/GiteaSCMSourceChecksContextTest.java
Labels: bugfix

#140 Fix release
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
Labels: chore

#142 Update pom
  pom.xml
Labels: chore

#136 Modernize plugin
  Jenkinsfile
  pom.xml
  src/main/java/io/jenkins/plugins/checks/gitea/GitSCMChecksContext.java
  src/main/java/io/jenkins/plugins/checks/gitea/GiteaChecksDetails.java
  src/main/java/io/jenkins/plugins/checks/gitea/GiteaChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/gitea/SCMFacade.java
  src/test/java/io/jenkins/plugins/checks/ArchitectureTest.java
  src/test/java/io/jenkins/plugins/checks/IntegrationTestBase.java
  src/test/java/io/jenkins/plugins/checks/gitea/GitSCMChecksContextITest.java
  src/test/java/io/jenkins/plugins/checks/gitea/GiteaChecksPublisherITest.java
Labels: dependencies, breaking, developer

#143 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore
